{
 "title": "Integrated Services HTTP Dashboard",
 "description": "HTTP metrics of Integrated Services.",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "app",
    "query": "label_values(app_kubernetes_io_instance)"
   }
  ]
 },
 "panels": [
  { "title": "At Glance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "# of Request",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(delta(opencensus_io_http_server_request_count{app_kubernetes_io_instance=\"$app\"}[1m]))",
     "legendFormat": "Today "
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 5, "x": 6, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(opencensus_io_http_server_response_count_by_status_code{http_status=\"500\",app_kubernetes_io_instance=\"$app\"}) / sum(opencensus_io_http_server_response_count_by_status_code{app_kubernetes_io_instance=\"$app\"}) * 100"
    }
   ]
  },
  {
   "title": "Avg Response Size",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 5, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rate(opencensus_io_http_server_response_bytes_sum{app_kubernetes_io_instance=\"$app\"}[1m])) / sum(rate(opencensus_io_http_server_response_bytes_count{app_kubernetes_io_instance=\"$app\"}[1m]))",
     "legendFormat": "Today "
    }
   ]
  },
  {
   "title": "95% Percentile Latency",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 5, "x": 18, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(opencensus_io_http_server_latency_bucket{app_kubernetes_io_instance=\"$app\"}[5m])) by (le))",
     "legendFormat": "Today "
    }
   ]
  },
  {
   "title": "Overall Latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "msec" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(opencensus_io_http_server_latency_bucket{app_kubernetes_io_instance=\"$app\"}[5m])) by (le))",
     "legendFormat": "50 percentile"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(opencensus_io_http_server_latency_bucket{app_kubernetes_io_instance=\"$app\"}[5m])) by (le))",
     "legendFormat": "95 percentile"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(opencensus_io_http_server_latency_bucket{app_kubernetes_io_instance=\"$app\"}[5m])) by (le))",
     "legendFormat": "99 percentile"
    }
   ]
  },
  {
   "title": "Request and Response BW",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short", "label": "Request bytes/sec" }
   ],
   "targets": [
    {
     "expr": "sum(rate(opencensus_io_http_server_request_bytes_sum{app_kubernetes_io_instance=\"$app\"}[5m]))",
     "legendFormat": "Request"
    },
    {
     "expr": "sum(rate(opencensus_io_http_server_response_bytes_sum{app_kubernetes_io_instance=\"$app\"}[5m]))",
     "legendFormat": "Response"
    }
   ]
  },
  {
   "title": "Latency Heatmap",
   "type": "heatmap",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "sum(increase(opencensus_io_http_server_latency_bucket{app_kubernetes_io_instance=\"$app\"}[10m])) by (le)"
    }
   ]
  },
  {
   "title": "Number of Response by Status",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "short", "label": "# of response / sec" }
   ],
   "targets": [
    {
     "expr": "sum by(http_status) (delta(opencensus_io_http_server_response_count_by_status_code{app_kubernetes_io_instance=\"$app\"}[1m]))",
     "legendFormat": "{{http_status}}"
    }
   ]
  }
 ]
}